import Link from 'next/link'

const sections = [
  {
    number: '1.',
    title: 'ACCEPTANCE OF TERMS',
    body: 'By accessing or using Nourishly ("the App"), operated by Nourishly Pty Ltd (ABN to be confirmed) ("we", "us", "our"), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.',
  },
  {
    number: '2.',
    title: 'DESCRIPTION OF SERVICE',
    body: 'Nourishly is a digital nutrition and recipe planning platform that uses artificial intelligence to generate personalised recipe suggestions based on user-provided health goals and dietary preferences. The App is intended for general wellness purposes only.',
  },
  {
    number: '3.',
    title: 'NOT MEDICAL ADVICE',
    body: 'IMPORTANT: Nourishly is not a medical service. The content generated by the App, including recipes, nutritional information, calorie targets, and ingredient substitutions, is for informational and general wellness purposes only. It does not constitute medical advice, diagnosis, or treatment.\n\nYou should always consult a qualified healthcare professional, registered dietitian, or nutritionist before making significant changes to your diet, particularly if you have a medical condition, allergy, eating disorder, or are pregnant or breastfeeding. Nourishly Pty Ltd expressly disclaims any liability for health outcomes resulting from reliance on App content.',
  },
  {
    number: '4.',
    title: 'AI-GENERATED CONTENT DISCLAIMER',
    body: 'Recipes, nutritional estimates, calorie calculations, and ingredient substitutions are generated by third-party artificial intelligence models. While we make reasonable efforts to ensure quality, AI-generated content may contain errors, inaccuracies, or omissions. Nutritional values are estimates only and should not be relied upon for medical or therapeutic dietary management. Nourishly Pty Ltd does not warrant the accuracy, completeness, or suitability of any AI-generated content.',
  },
  {
    number: '5.',
    title: 'USER ACCOUNTS',
    body: 'You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 13 years of age to use the App. You agree not to use the App for any unlawful purpose.',
  },
  {
    number: '6.',
    title: 'HEALTH DATA',
    body: 'By using the App, you voluntarily provide sensitive health information including but not limited to your health goals, dietary restrictions, body weight, height, age, and meal logs. You acknowledge that this information is used solely to personalise your experience within the App. You may request deletion of your health data at any time by contacting us at privacy@nourishly.app.',
  },
  {
    number: '7.',
    title: 'INTELLECTUAL PROPERTY',
    body: 'All content, design, logos, and software comprising the App are the intellectual property of Nourishly Pty Ltd unless otherwise stated. You may not reproduce, distribute, or create derivative works without our express written permission. AI-generated recipes provided to you through the App are licensed for your personal, non-commercial use only.',
  },
  {
    number: '8.',
    title: 'LIMITATION OF LIABILITY',
    body: 'To the maximum extent permitted by Australian law, Nourishly Pty Ltd, its directors, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to: adverse health outcomes from following AI-generated recipes or nutritional advice; allergic reactions or dietary complications; data loss or service interruption; loss of profits or business opportunities. Our total liability to you for any claim arising from use of the App shall not exceed the amount you paid to us in the 12 months preceding the claim, or AUD $100, whichever is greater.',
  },
  {
    number: '9.',
    title: 'THIRD PARTY SERVICES',
    body: 'The App uses the following third-party services which have their own terms and privacy policies: Supabase (database and authentication), Groq (AI model inference). We are not responsible for the practices of these third parties.',
  },
  {
    number: '10.',
    title: 'GOVERNING LAW',
    body: 'These Terms are governed by the laws of New South Wales, Australia. Any disputes shall be subject to the exclusive jurisdiction of the courts of New South Wales.',
  },
  {
    number: '11.',
    title: 'CHANGES TO TERMS',
    body: 'We may update these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms.',
  },
  {
    number: '12.',
    title: 'CONTACT',
    body: 'For questions about these Terms, contact us at legal@nourishly.app',
  },
]

export default function TermsPage() {
  return (
    <div style={{ background: 'var(--color-bg)', minHeight: '100vh', padding: '48px 24px' }}>
      <div style={{ maxWidth: 720, margin: '0 auto' }}>

        <Link
          href="/register"
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            fontSize: '0.875rem',
            color: 'var(--color-text-3)',
            textDecoration: 'none',
            marginBottom: 32,
          }}
        >
          ← Back
        </Link>

        <h1 style={{
          fontFamily: 'var(--font-display), system-ui, sans-serif',
          fontWeight: 700,
          fontSize: '2rem',
          color: 'var(--color-text)',
          margin: '0 0 8px',
          letterSpacing: '-0.5px',
        }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: '0.875rem', color: 'var(--color-text-3)', margin: '0 0 40px' }}>
          Last updated: July 2026
        </p>

        {sections.map((section) => (
          <div
            key={section.number}
            style={{
              borderBottom: '1px solid var(--color-border)',
              padding: '20px 0',
            }}
          >
            <h2 style={{
              fontFamily: 'var(--font-display), system-ui, sans-serif',
              fontWeight: 700,
              fontSize: '0.95rem',
              color: 'var(--color-text)',
              margin: '0 0 10px',
              display: 'flex',
              gap: 8,
              alignItems: 'baseline',
            }}>
              <span style={{ color: 'var(--color-green)', fontWeight: 700, minWidth: 28 }}>
                {section.number}
              </span>
              {section.title}
            </h2>
            {section.body.split('\n\n').map((para, i) => (
              <p key={i} style={{
                fontSize: '0.9rem',
                color: 'var(--color-text-2)',
                lineHeight: 1.8,
                margin: i > 0 ? '12px 0 0' : '0',
              }}>
                {para}
              </p>
            ))}
          </div>
        ))}

      </div>
    </div>
  )
}
